package vu.lt.mybatis.model;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Mon May 02 16:44:22 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.AGE
     *
     * @mbg.generated Mon May 02 16:44:22 EEST 2022
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Mon May 02 16:44:22 EEST 2022
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Mon May 02 16:44:22 EEST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @return the value of PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Mon May 02 16:44:22 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.ID
     *
     * @param id the value for PUBLIC.CUSTOMER.ID
     *
     * @mbg.generated Mon May 02 16:44:22 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.AGE
     *
     * @return the value of PUBLIC.CUSTOMER.AGE
     *
     * @mbg.generated Mon May 02 16:44:22 EEST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.AGE
     *
     * @param age the value for PUBLIC.CUSTOMER.AGE
     *
     * @mbg.generated Mon May 02 16:44:22 EEST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @return the value of PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Mon May 02 16:44:22 EEST 2022
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.LASTNAME
     *
     * @param lastname the value for PUBLIC.CUSTOMER.LASTNAME
     *
     * @mbg.generated Mon May 02 16:44:22 EEST 2022
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CUSTOMER.NAME
     *
     * @return the value of PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Mon May 02 16:44:22 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CUSTOMER.NAME
     *
     * @param name the value for PUBLIC.CUSTOMER.NAME
     *
     * @mbg.generated Mon May 02 16:44:22 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}